steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - "USERNAME=${USERNAME}"
      - "PASSWORD=${PASSWORD}"
      - "CLUSTER=${CLUSTER}"
      - "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}"
      - "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}"
      - "ARN_HASHTAG_STATE_MACHINE=${ARN_HASHTAG_STATE_MACHINE}"
      - "ROLE_ARN_AMAZON_EVENTBRIDGE_SCHEDULER=${ROLE_ARN_AMAZON_EVENTBRIDGE_SCHEDULER}"
      - "SERVER_URL_ECO=${SERVER_URL_ECO}"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"